### PR TITLE
Convert XLF to YAML translations

### PR DESCRIPTION
**Pull request by astroidex**

### CODE REVIEW

**Review by eSlider — APPROVED** [review]

**Comment by astroidex** [comment]
please. merge

**Review by werrolf — APPROVED** [review]

**Comment by LazerTiberius** [comment]
Is it consent that we move from XLF to YML translation?

**Review by DavidPatzke — APPROVED** [review]

**Comment by astroidex** [comment]
Hi @LazerTiberius - I think yes. Benno and I and others (FOSS4G translation sprint in july 2017) helped with the translations. Results are in Branch hotfix/translations in every repository 
f.e.
https://github.com/mapbender/mapbender/tree/hotfix/translations

**Comment by werrolf** [comment]
Should also be safe to merge into 3.0.6 series. Anyone disagree?

**Comment by AxxL** [comment]
@werrolf It's a feature, a change in the behaviour. Developers don't expect to have a different translation system.

**Pull request merged**
